### PR TITLE
deps: handlebars@4.0.5

### PR DESCRIPTION
**Pull request by jaswilli**

### CODE REVIEW

**Comment by mgutz** [comment]
@ErisDS Are you able to update npm? I think there were issues some time back.

**Comment by ErisDS** [comment]
@mgutz yeah I believe so - gonna make a couple more amends first and then will publish a new version

**Comment by ktkaushik** [comment]
👍

**Comment by ktkaushik** [comment]
@ErisDS please let us know if you can up the version at the earliest.

**Comment by ErisDS** [comment]
@ktkaushik v1.0.0 is now available

**Comment by ktkaushik** [comment]
@ErisDS 👍  thanks

**Pull request merged**
