### PR TITLE
enabling travis ci

### PR DESCRIPTION
**Pull request by olsio**
Added .travis.yml to allow travis ci run automatic tests.

### CODE REVIEW

**Comment by mgutz** [comment]
Thank you for PRs. I'm currently in Techstars and our demo day is next week. Haven't had much time to look at any of issues. Please bear with me for another couple of weeks.

**Comment by ErisDS** [comment]
Have taken a quick look at this - 0.10 is in the list twice. I also think it makes sense to test only the LTS versions of > 0.12 so just 4.2 and no need for 4.0 and 4.1? I guess as the build is super fast it doesn't matter too much, but once you go over the concurrent build limit you can end up waiting a while for Travis to start.

**Comment by ErisDS** [comment]
@mgutz I was looking at cleaning this up and getting it live - but I don't have the ability to enable travis for this repo. Can you look at doing it or escalating me to an admin so that I can?

**Comment by mgutz** [comment]
@ErisDS You should now have admin privileges.

**Comment by ErisDS** [comment]
@mgutz 👍

**Comment by ErisDS** [comment]
Fixed-up & manually merged

**Pull request closed without merging**
